/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppNavbar {
    }
    interface InsuranceChat {
    }
}
declare global {
    interface HTMLAppNavbarElement extends Components.AppNavbar, HTMLStencilElement {
    }
    var HTMLAppNavbarElement: {
        prototype: HTMLAppNavbarElement;
        new (): HTMLAppNavbarElement;
    };
    interface HTMLInsuranceChatElement extends Components.InsuranceChat, HTMLStencilElement {
    }
    var HTMLInsuranceChatElement: {
        prototype: HTMLInsuranceChatElement;
        new (): HTMLInsuranceChatElement;
    };
    interface HTMLElementTagNameMap {
        "app-navbar": HTMLAppNavbarElement;
        "insurance-chat": HTMLInsuranceChatElement;
    }
}
declare namespace LocalJSX {
    interface AppNavbar {
    }
    interface InsuranceChat {
    }
    interface IntrinsicElements {
        "app-navbar": AppNavbar;
        "insurance-chat": InsuranceChat;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-navbar": LocalJSX.AppNavbar & JSXBase.HTMLAttributes<HTMLAppNavbarElement>;
            "insurance-chat": LocalJSX.InsuranceChat & JSXBase.HTMLAttributes<HTMLInsuranceChatElement>;
        }
    }
}
